In [1]:
import numpy as np

![title](softmax-hinge.png)

In [14]:
x = np.array([-15,22,-44,56])
W = np.array([[0.01,-0.05,0.1,0.05],[0.7,0.2,0.05,0.16],[0,-0.45,-0.2,0.03]])
b = np.array([0,0.2,-0.3])

scores = W.dot(x) + b

In [15]:
scores

array([-2.85,  0.86,  0.28])

In [19]:
def hinge_loss(scores,y):

    delta = 1.0
    # compute the margins for all classes in one vector operation
    margins = np.maximum(0, scores - scores[y] + delta)
    # on y-th position scores[y] - scores[y] canceled and gave delta. We want
    # to ignore the y-th position and only consider margin on max wrong class
    margins[y] = 0
    loss_i = np.sum(margins)
    return loss_i

In [32]:
def softmax(scores,y):
    exp_score = np.exp(scores) 
    np.set_printoptions(precision=3)
    print(exp_score)
    norm_score = exp_score/ np.sum(exp_score)
    print(norm_score)
    loss_i = - np.log(norm_score[y])
    return loss_i

In [34]:
true_label = 2
print('hinge loss = %.2f'% hinge_loss(scores,true_label))
print('softmax loss = %.2f'% softmax(scores,true_label))

hinge loss = 1.58
[0.058 2.363 1.323]
[0.015 0.631 0.353]
softmax loss = 1.04
